package com.soywiz.korge.tictactoe

import com.soywiz.korge.animate.AnLibrary
import com.soywiz.korge.resources.getPath
import com.soywiz.korio.inject.AsyncInjector

// AUTOGENERATED:
fun AsyncInjector.generatedInject() = this
	//.mapPrototype { TicTacToeMainScene(getPath("main.ani")) } // @TODO: kotlin.js bug
	//.mapPrototype { TicTacToeMainScene(getPath(AnLibrary::class, "main.ani")) }
	.mapPrototype { TicTacToeMainScene() }
